name: DevOpsLab Pipeline

on:
  push:
    branches:
      - main
      - new-pipeline
jobs:
  Build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Clone do Repositório
        uses: actions/checkout@v2
      - name: Login no Google Artifact Registry
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
        run: | 
          echo '${{ secrets.GCP_CREDENTIALS }}' > key.json
          cat key.json | docker login -u _json_key --password-stdin '${{ vars.GOOGLE_ARTIFACT }}' 
      - name: Build Imag & Push para Google Registry
        env:
          ARTIFACT_REGISTRY: ${{ secrets.ARTIFACT_REGISTRY }}
          BACKEND_URL: ${{ secrets.BACKEND_URL }}
        run: |
          docker build -t ${{ vars.GOOGLE_ARTIFACT }}/${{ vars.GOOGLE_PROJECT_ID }}/${{ vars.ARTIFACTREGISTRY_REPOSITORY }}/${{ vars.GOOGLE_MYAPPNAME }}:latest --build-arg BACKEND_URL=${{ vars.REACT_APP_BACKEND_URL }} .
          docker push ${{ vars.GOOGLE_ARTIFACT }}/${{ vars.GOOGLE_PROJECT_ID }}/${{ vars.ARTIFACTREGISTRY_REPOSITORY }}/${{ vars.GOOGLE_MYAPPNAME }}:latest
      - name: Show file
        run: cat src/App.js

  Deploy:
    needs: Build
    runs-on: ubuntu-latest

    steps:
      - name: Clone do Repositório
        uses: actions/checkout@v2

      - name: Autenticação no Google Cloud
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: Deploy Frontend no  Cloud Run
        id: deploy
        run: |-
          gcloud run deploy frontend \
            --quiet \
            --image ${{ vars.GOOGLE_ARTIFACT }}/${{ vars.GOOGLE_PROJECT_ID }}/${{ vars.ARTIFACTREGISTRY_REPOSITORY }}/frontend:latest \
            --platform managed \
            --allow-unauthenticated \
            --project ${{ vars.GOOGLE_PROJECT_ID }} \
            --format json
